### ISSUE TITLE
Input validation failed

### ISSUE THREAD

**Issue by sotiris84** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#6]
# Module: 02
##### Step: 2

Description of issue
The lab steps say to create an Azure Automation account and choose "any unique name". I have entered a large number of unique and random names but validation always fails. I am using godeploy.it lab environment.

Repro steps:
Just follow the steps

![Screenshot 2022-03-13 144157](https://user-images.githubusercontent.com/1143552/158059918-b984472c-755d-430c-b5eb-4b393f6f82d0.jpg)

**Comment by craigbeeremct** [comment]
Based on that resource group name, I'm guessing the lab is using Go Deploy's Cloud Share feature. Possibly they have some policy on names (perhaps a maximum length). Your first point of contact should be Go Deploy.

That name you've picked is certainly available (just not right now, because I've created an Automation Account using that name to test it).

**Comment by sotiris84** [comment]
@craigbeeremct Than you for your time and reply. You are right this is godeploy (I mentioned it I believe in the op). I did raise a case with their support (which was very quick I have to admit) and I was provided with a response that it should be fixed. I have not tested it due to time constraints, but I will report here as soon as I verify.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by TJGitHubUser** [comment]
Closing issue #6 as it was subsequently tested, and issue was not experienced.
